sudo: false

language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'

before_install:
- yes | sdkmanager "platforms;android-27"

jdk:
  - oraclejdk8

script:
- "./gradlew :library:createDebugAndroidTestCoverageReport --info --stacktrace"
- "./gradlew build"

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

dist:
- trusty
after_success:
- bash <(curl -s https://codecov.io/bash)
after_failure:
- if [ -f /home/travis/build/pre-dem/pre-dem-android/example/build/reports/lint-results.html
  ]; then lynx -dump /home/travis/build/pre-dem/pre-dem-android/example/build/reports/lint-results.html;
  fi
before_install:
- gem install fir-cli
after_deploy:
- fir p example/build/outputs/apk/example-release.apk -T $FIR_TOKEN -c "`git cat-file
  tag $TRAVIS_TAG`"
notifications:
  email:
  - apm@qiniu.com
deploy:
  provider: releases
  api_key:
    secure: lLM2m7789qsu78fqvgME6LqNEgKst8ypNK73mKmF769QWLvbJqPUe8fJG5Zsbgu+x/nwes/6S3cb9L/4iUy7/1oqht06KK0YD2Vv5/jSjlZcjNmQj/+dFPt/yzT6ILtL/tuFpcSIXJLHDfrnu7k4r3c4fEn94pLmD161PeXZNLwCliXUQLgENYWw6VxUD+2Bcg8KKOQxY0j4ob8fdp6tH2/FY4WaB4AtOt/B4SV9R6lxRm2KpoQGB3MXZO2rhx0Aib+4JB7o+cdqiDhd8B37QpPuuoNteMJdqtSmcF0gRSRdXXENivBs7L1ujB3d8bDy9jTjCr2FVRxU1TC263AwJ0G2eKS55WeiYqPtD21sVVwv9TNGnMMFwinm8Ub+sIyXVBEEI4LomXtzEsj7YYz3q+SaWr4uj0Oekt3xL3JhmPYqf77lFWXC44HZlz8k/G/B+Nqc6N5JreOOY/M3ojqvVNib4EQUIUW3Z1mG0QLQvk8gYgOrq94c0R3RCCbzPxwSvHf2Z0v4+PYAxS7f8fy0eTqnmmnWbN/RkHuM9FmUm4JA0iU8zgQ50cqzspPDMOm7ZJAlLR3smQjhiZIEZWe6G5WCfx3rqcAeqbO5peq4CqFPGuXknU/Khjg4Fck3hprFhKfZcmzzG+QB6+/3KQuSjELRfBKuPZOWd903gfejG3o=
  file: example/build/outputs/apk/example-release.apk
  skip_cleanup: true
  on:
    repo: pre-dem/pre-dem-android
